export const INDICES = '/indices'
export const STAKING = '/staking'
export const LIQUIDITY = '/staking/liquidity'
export const GOVERNANCE = '/governance'
export const VAULT = '/vault'
export const LANDING = '/'
